# Generated by Django 4.2.6 on 2024-04-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_background_useraccount_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='artistname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
