# Generated by Django 4.2.6 on 2024-04-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='key',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
